### ISSUE TITLE
Console versions should not change console properties

### ISSUE THREAD

**Issue by jsakamoto** [jsakamoto/CSharpProlog#13]
I think, Console versions should not change console properties.

One of the reason, PLd.exe always crash on my PC because the screen resolution of my PC is no enough.

![image](https://user-images.githubusercontent.com/95908/39082226-89f9892a-458a-11e8-939e-ece22a4cad09.png)

**Comment by poolofthought** [comment]
Sounds reasonable. Or maybe we can add the desired size to a config file that the user can set?

**Comment by jsakamoto** [comment]
In my opinion, any console applications should not change console window properties.

For example, if Python or Ruby "irb" changes my console window position and window size and font color, then I will feel uncomfortable.

> Or maybe we can add the desired size to a config file that the user can set?

Thank you for your proposal. 👍  
I think it is not a bad idea, but I can not find enough value to take the trouble of implementing that function at this time.

If is there anyone who prefer the PLd app that changes console window position/size/font color, they can still use ver.5 binary, So I would like to remove all part of the codes about changing console window properties from vNext versions.

**Comment by poolofthought** [comment]
try out that branch and make sure it takes care of the resizing thing. If so I'll make a pull request. I don't have a windows box to test this on right now, but I believe that should do it.

**Comment by poolofthought** [comment]
I'm going to update this a little further, actually. The help listing only has 5 columns, which is too many for an unmodified console size. It we take it down to three columns it will be less than the standard 80 chars wide - so the output of the help will look nice and lined up again.

**Comment by poolofthought** [comment]
The help is now 80 columns wide. Please pull this branch on windows and give it a test. If it works I'll create a pull request and we can mark this issue as done!

**Comment by jsakamoto** [comment]
I tried "console-keep-size" branch on Windows, and I works very well.

Looks of "help" is also good.

I'll accept a pull request for this issue if you send to me.

By the way, this branch's version still changes font color.  
How do you think about this?

In my opinion, CSharpProlog console apps should not change font color too, I think.

**Comment by poolofthought** [comment]
> By the way, this branch's version still changes font color.
How do you think about this? In my opinion, CSharpProlog console apps should not change font color too, I think.

I am of two minds. I kind of like the white background and dark font. It makes it easy to spot your interpreter window, and since the color is only changed while the program is running it's not a big deal. But I also understand that some people pick the themes they want and don't want someone else to pick it for them. 

Go ahead and add an issue to remove the automatic color selection and at some point I'll look at it. I might look at adding a simple predicate to set an interpreter theme. In that case it would default to whatever the user's computer settings are, but with one 'command' user could change to a different theme. 

I'll submit the pull request for #13 change now.

**Comment by poolofthought** [comment]
Actually, I don't know which branch I should pull request to... vnext?

**Comment by jsakamoto** [comment]
Thanks for your reply.

Yes, please create pull request to `vnext/master` branch. (see also: #14 )
