### ISSUE TITLE
Get all solutions of a query

### ISSUE THREAD

**Issue by BlackstarMC97** [jsakamoto/CSharpProlog#2]
Hello, i want to know how i can get and use all solutions of a query?

**Comment by jsakamoto** [comment]
like this:

```csharp
using System;
using Prolog;

class Program
{
    static void Main(string[] args)
    {
        var prolog = new PrologEngine(persistentCommandHistory: false);

        // 'socrates' and 'plato' is human.
        prolog.ConsultFromString(
            "human(socrates).\n" +
            "human(plato).");

        // human is bound to die.
        prolog.ConsultFromString("mortal(X) :- human(X).");

        // Question: Who shall die?
        prolog.Query = "mortal(X).";
        foreach (var solution in prolog.GetEnumerator())
        {
            foreach (var val in solution.VarValuesIterator)
            {
                Console.WriteLine($"{val.Name} is {val.Value}");
            }
        }
    }
}
```

The result is here:

![image](https://user-images.githubusercontent.com/95908/35946175-28ce0f12-0ca6-11e8-83b9-feefc59569be.png)

1. You should setup `Query` property of a `PrologEngine` object with the query what you want to get solutions.
2. After setting up of `Query` property, you can enumerate all solutions of that query via `GetEnumerator()` method of a `PrologEngine` object.

P.S.  
`PrologEngine` class has `GetAllSolutions()` method, but it is hard to use in this scenario, because `GetAllSolutions()` method require source file name with 1st argument.  
I'll consider change this method signature to fit with `GetFirstSolution()` method.

**Comment by BlackstarMC97** [comment]
Thank you, I used the GetAllSolutions() method like this : 

           `prolog.Consult("codeprolog.pl");
            SolutionSet resultat = new SolutionSet();
            result = prolog.GetAllSolutions("codeprolog.pl", query: "myquery");

            foreach (Solution x in result.NextSolution)
            {
                 foreach (Variable y in x.NextVariable)
                 {
                      ... // Use y.Value
                 }
            }
`
I find your library great, can I have his complete documentation?

**Comment by jsakamoto** [comment]
> can I have his complete documentation?

Sorry, this project is forked project from https://sourceforge.net/projects/cs-prolog/ , so it is maybe hard work to me.

I'm also not sure about deep level of this program.
