### ISSUE TITLE
How can a fact be queried ?

### ISSUE THREAD

**Issue by MajidAliKhanQuaid** [jsakamoto/CSharpProlog#28]
like

query('what is your name', 'majid').
?- query('what is your name', Name).

Unable to get value of Name variable

**Comment by poolofthought** [comment]
You would need to either "consult" the fact from a file so that it is in the prolog database OR if you don't want to put the fact into a file you can "assert" it. It POSSIBLE that single quotes won't work, but my guess is that you haven't added the fact and that's why you can't unify Name to the value you expect.

**Comment by poolofthought** [comment]
As far as I can tell it works fine with single quotes also. So my guess is you just don't actually have the fact in the database.

4 ?- assert(query('what is your name', 'majid')).   

true

5 ?- query('what is your name', Name).

 Name = majid

6 ?-

**Comment by poolofthought** [comment]
Closing issue. Tests and example show it works.
