### ISSUE TITLE
CHAT folder missing

### ISSUE THREAD

**Issue by poolofthought** [jsakamoto/CSharpProlog#3]
There is mention in CSProlog\bootstrap.cs of a CHAT folder that should be part of the repo. If you type chat it tries but can't find the file.  

Is this something that was intentionally left out? Maybe couldn't be found? I think if the example code can't be found it's probably better removed from the comments also. It sure would be nice if we could find it and put it back in (assuming it wasn't left out on purpose), but the link mentioned in the comments is also dead. :(

Note: this is my first putting of an issue on someone else's repo so please forgive me if I've gone about it wrong. I'm open to correction.

**Comment by poolofthought** [comment]
I see now I can add an issue to my own fork if I enable it. However, since you ported it from JohnPool's original repo I'm wondering if anything was intentionally left off and if I should even bother trying to dig it up. Thoughts? Thanks in advance.

**Comment by jsakamoto** [comment]
Thank you for your reporting!

I'm sorry to late because I was very busy for another some projects.

Anyway, I'll figure out this issue.

**Comment by jsakamoto** [comment]
I researched about this issue on internet for a few hours.

The result of researching is this:

Fact
-----------
- "CHAT-80" is a software that is copyrighted by Fernando Pereira.
- "CHAT-80" is not a part of CSharpProlog. CSharpProlog is not licensed to redistribute "CHAT-80".
- "chat" predefined predicate of CSharpProlog is provided for just a shortcut to launching "CHAT-80", for convenience to users.
- Getting "CHAT-80" program files, and storing it into "chat-80" subfolder, are responsible of individual users.
- But, today, original "CHAT-80" program files were gone due to the distribution point web site (http://www.cis.upenn.edu/~pereira/oldies.html) was closed.
- I found a part of "CHAT-80" program files in internet archives. But it is not full set, so we can't try "chat"  predicate.



Conclusion
-----------
I will remove "chat" predicate from predefined predicates, and release new version of CSharpProlog.

**Comment by jsakamoto** [comment]
P.S.

I found "SAMPLES, TESTING & EXPERIMENTAL" section in predefined predicates.  
That section include like these noisy predicates... :O !

```
age( peter, 7).
age( ann, 5).
age( ann, 6).
age( pat, 8).
age( tom, 5).
``` 

I think that these predicates are not suitable for predefined predicates.

Therefore, I'll remove all of the "SAMPLES, TESTING & EXPERIMENTAL" section from predefined predicates.

**Comment by poolofthought** [comment]
I think that's a great idea. I'm going to submit a pull request for what I've been doing. If nothing else I'd like your comments on it. Nothing major (added a dotnetcore console app that works in linux, updated help text, etc). I THINK it will merge okay with the changes you are suggesting. I just don't want our forks to diverge too far.

**Comment by jsakamoto** [comment]
Thank you for your contributions! 👍 
I found your pull request on this GitHub repository.

I'll merge your pull request after I understand what did you do.

Unfortunately, I have a task that higher priority just now, so please give me one or few days to merge your pull request.

**Comment by poolofthought** [comment]
No problem. My notes on the pull request itself will probably be better to help you understand than the commits. The reason is that in one commit I might have done something that worked, but then found a better way and committed that later. We can continue that conversation on the pull request itself. :)

**Comment by jsakamoto** [comment]
P.S. I'm started using GitHub project feature.

See: https://github.com/jsakamoto/CSharpProlog/projects/1

**Comment by jsakamoto** [comment]
I did it at 5f00b5eee8eed422130b2ce5a5a83080225fd45
